"""
This type stub file was generated by pyright.
"""

class Cursor:
    def __init__(self, source_string) -> None:
        ...
    
    def is_done(self): # -> bool:
        ...
    
    def next(self): # -> None:
        ...
    
    def peek(self): # -> Literal['']:
        ...
    
    def get(self):
        ...
    
    def get_remaining(self): # -> str:
        ...
    
    def move_past_next(self, symbols): # -> None:
        ...
    
    def contains_any(self, symbols): # -> bool:
        ...
    
    def get_until(self, symbols, positive_match=...): # -> Literal['']:
        ...
    


