"""
This type stub file was generated by pyright.
"""

from enum import Enum
from dataclasses import dataclass

class ElementType(Enum):
    SECTION = ...
    ALTERNATION_SECTION = ...
    ATOMIC = ...


@dataclass
class ResolvedElement:
    prefix: str
    index: int
    suffix: str
    args: dict
    def to_str(self) -> str:
        ...
    


class Element:
    def __init__(self) -> None:
        ...
    
    def add(self):
        ...
    
    def decompile(self, recursion=...): # -> str:
        ...
    
    def get_information_array_ordered(self): # -> list[Any]:
        ...
    


