"""
This type stub file was generated by pyright.
"""

from shuttle_notation.parsing.element import Element, ResolvedElement

class Parser:
    def __init__(self) -> None:
        ...
    
    def parse(self, source_string: str) -> list[ResolvedElement]:
        ...
    
    def resolve(self, element: Element) -> ResolvedElement:
        ...
    


