"""
This type stub file was generated by pyright.
"""

from shuttle_notation.parsing.element import Element

"""

Parsing logic related to "()"-sections, "/"-alternation and "x"-repetition. 

"""
def build_tree(source_string) -> Element:
    ...

