"""
This type stub file was generated by pyright.
"""

def section_split(source_string) -> list:
    ...

class TreeExpander:
    def __init__(self) -> None:
        ...
    
    def count_required_alternations(self, element): # -> Literal[1]:
        ...
    
    def all_ticked(self, element) -> bool:
        ...
    
    def tree_expand(self, element) -> list:
        ...
    
    def tick(self, element): # -> None:
        ...
    
    def get_ticks(self, element): # -> int:
        ...
    
    def expand(self, element, repeat) -> list:
        ...
    


def get_repeat(element) -> int:
    ...

def duplicate(elements, times): # -> list[Any]:
    ...

def get_information_history(element) -> list:
    ...

def resolve_full_arguments(information_history: list, default_args: dict = ..., arg_aliases: dict = ...) -> dict:
    ...

